---
title: "Gov 50 Final Project"
author: "Sebastian Ramirez Feune"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---


## Project thoughts

I am interested in exploring data related to race and Latinidad. I would like to find data on who identified as "Latino/Hispanic" in the most recent census in major cities across the USA. With this data, I would like to observe the racial proportions of those identifying as Latino or Hispanic: whether they identify as Black, White, Indigenous, Asian, Pacific Islander, or Other. Additionally, I would also like for my data to include their income levels. This way, I will be able to track the general regional trends of how Latinos across the USA racially identify, comparing Latinos in New York City to those in Los Angeles, and so on. My end goal is to see if there are any regional concentrations in the United States where Latinos identify as a certain race more than other regions, and if there is any link between the self-identified race and income level of those respondents.

## Milestone 2
How have total incomes among members of different racial groups trended between the years 1970 and 2020? In this study, I will compare the growth of the average total incomes of five racial groups over a span of 50 years. I hypothesize that the US Census Bureau Data will reveal that generally, white and Asian US citizens have had steeper increases in income than Black and Hispanic communities. This argument is predicated on the presence of institutional racism in the United States. Likewise, the data will likely reflect the increasing racial wage gap that disproportionately affects Black and Hispanic Americans. The explanatory variables that I will look into are the different racial categorie. These would be the racial categories of “Black,” “White (Non-Hispanic),” “Asian,” Hispanic (All Races),” “Pacific Islander,” and “Other.” The outcome variable will be the total average income for the racial group. This will be measured in dollars over the 50 years between 1970 and 2020, spaced by one year increments. From here, I will look at the linear regression of the data over the years and see which racial groups have had the most dramatic/steepest growth. If the white and Asian American average total incomes tend to have steeper slopes than those for Black and Hispanic Americans, this will support my hypothesis that specifically disadvantaged groups, more specifically Hispanic and Black Americans, saw less dramatic total income growth in the last 50 years than white and Asian Americans. My hypothesis would be disproved if there were more dramatic growth within the Black and Hispanic demographic than the white and Asian. Furthermore, if there is a net decrease in income for any racial demographic over those 50 years, then that will further disprove my hypothesis. 
